version: '3.6'
services:
  server:
    image: melchor9000/dnscrypt-proxy
    ports:
      - target: 5353
        published: 53
        protocol: udp
        mode: host
    restart: always
    volumes:
      - "./config:/etc/dnscrypt-proxy"
    deploy:
      mode: replicated
      replicas: 2