version: "3"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8088:8088
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  qbittorrent2:
    image: linuxserver/qbittorrent
    container_name: qbittorrent2
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Asia/Kolkata
    - UMASK_SET=022
    - WEBUI_PORT=8088
    volumes:
    - ./config:/config
    - ${ROOT}/downloads:/downloads
    restart: unless-stopped
    network_mode: "service:wireguard"
