version: "3"
services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config:/config
      - ${ROOT}/complete/music:/music
      - ${ROOT}/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
